parameters:
#    tortillator_api_tortillator.example.class: TortillatorAPI\TortillatorBundle\Example

services:
#    tortillator_api_tortillator.example:
#        class: %tortillator_api_tortillator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
